# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12654dcc00f829740af7fc11d0746058c46861b8efb3c0405ecdb36db71dfad926b800849ca2cf096605f6945d1d39cd269d09582cfeb0fb28d2b4663d0c14c0

test:
  secret_key_base: 099a9ae84b78da38ec15259aca46de0b5090e6a0a7d9f9a997350f7887bfe3c6bac68869163560060190718bef65a5c9c5c1724f12a5fc087703591da3767808

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
